### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by olifre** [elemental-lf/benji#11]
Attempting to export a version via NBD which is valid and not concurrently accessed, the following happens:

```
    INFO: Starting to serve NBD on 127.0.0.1:10809
    INFO: Incoming connection from 127.0.0.1:53868
    INFO: [127.0.0.1:53868] Negotiated export: V0000000002
   ERROR: Task exception was never retrieved
future: <Task finished coro=<NbdServer.handler() done, defined at /opt/benji/lib64/python3.6/site-packages/benji/nbdserver.py:112> exception=InternalError('Attempt to release lock "V0000000002" even though it isn\'t held',)>
Traceback (most recent call last):
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/benji/lib64/python3.6/site-packages/benji/database.py", line 1054, in lock
    self._session.commit()
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 954, in commit
    self.transaction.commit()
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2313, in flush
    self._flush(objects)
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2440, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2404, in _flush
    flush_context.execute()
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
    uow
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 836, in _emit_insert_statements
    execute(statement, multiparams)
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/benji/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: 'INSERT INTO locks (host, process_id, lock_name, reason, date) VALUES (?, ?, ?, ?, ?)'] [parameters: ('backup.virt.physik.uni-bonn.de', '7e6f9db0137511e9b9fe003048c63494', 'V0000000002', 'NBD', '2019-01-08 18:44:58.876437')] (Background on this error at: http://sqlalche.me/e/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/benji/lib64/python3.6/site-packages/benji/nbdserver.py", line 178, in handler
    self.store.open(version)
  File "/opt/benji/lib64/python3.6/site-packages/benji/benji.py", line 1120, in open
    self._benji_obj._locking.lock_version(version.uid, reason='NBD')
  File "/opt/benji/lib64/python3.6/site-packages/benji/database.py", line 1117, in lock_version
    locked_msg='Version {} is already locked.'.format(version_uid.v_string))
  File "/opt/benji/lib64/python3.6/site-packages/benji/database.py", line 1058, in lock
    raise AlreadyLocked(locked_msg)
benji.exception.AlreadyLocked: Version V0000000002 is already locked.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/benji/lib64/python3.6/site-packages/benji/nbdserver.py", line 309, in handler
    self.store.close(version)
  File "/opt/benji/lib64/python3.6/site-packages/benji/benji.py", line 1123, in close
    self._benji_obj._locking.unlock_version(version.uid)
  File "/opt/benji/lib64/python3.6/site-packages/benji/database.py", line 1126, in unlock_version
    self.unlock(lock_name=version_uid.v_string)
  File "/opt/benji/lib64/python3.6/site-packages/benji/database.py", line 1091, in unlock
    raise InternalError('Attempt to release lock "{}" even though it isn\'t held'.format(lock_name))
benji.exception.InternalError: Attempt to release lock "V0000000002" even though it isn't held
```
Since a backup of a different snapshot of the same image was performed in parallel, the database lock is fully expected. 

Not sure if this *should* really work, but it should at least not crash :wink: .

**Comment by elemental-lf** [comment]
Seems to be a locking issue of the SQLite3 database. Are your database files on an NFS (or other network filesystem) mounted volume?

**Comment by olifre** [comment]
This was on a local ext4, interestingly.

**Comment by elemental-lf** [comment]
On closer inspection this seems to be a design choice of SQLite. I found this in the SQLAlchemy documentation:

> However, no matter what locking modes are used, SQLite will still always lock the database file once a transaction is started and DML (e.g. INSERT, UPDATE, DELETE) has at least been emitted, and this will block other transactions at least at the point that they also attempt to emit DML. By default, the length of time on this block is very short before it times out with an error.

I've pushed a workaround which might help in https://github.com/elemental-lf/benji/commit/3d95bfc621686e8908be11d07fa255493b392dca. But the advise is to use PostgreSQL.

I'll keep this issue open as a documentation TODO.

**Comment by olifre** [comment]
Thanks! Yes, that sounds reasonable, also the workaround.
