### ISSUE TITLE
IO Scheme k8s is undefined

### ISSUE THREAD

**Issue by kenandervisevic** [elemental-lf/benji#111]
**Describe the bug**

I get the following error when I try to run the `benji-backup-pvc` script: `RuntimeError: benji invocation failed with return code 78 and output: {"event": "ConfigurationError: IO scheme k8s is undefined.", "level": "error", "timestamp": 1618768038.606371, "file": "/benji/lib64/python3.6/site-packages/benji/scripts/benji.py", "line": 373, "function": "main", "process": 4936, "thread_name": "MainThread", "thread_id": 140412611688256}`

Backup of one particular volume works. For example `benji-command backup rbd:k8s/kubernetes-dynamic-pvc-aa337a12-9ddb-11eb-ab3e-6e28514eb42d test` runs without any issues.

Full output:
```
bash-4.2# benji-backup-pvc 
Backing up all PVCs in all namespaces.
Newest RBD snapshot is k8s/kubernetes-dynamic-pvc-aa337a12-9ddb-11eb-ab3e-6e28514eb42d@b-2021-04-18T17:25:44Z.
Existing RBD snapshot k8s/kubernetes-dynamic-pvc-aa337a12-9ddb-11eb-ab3e-6e28514eb42d@b-2021-04-18T17:25:44Z not found in Benji, deleting it and reverting to initial backup.

Removing snap: 100% complete...done.
Performing initial backup of benji/data-benji-postgresql-0:k8s/kubernetes-dynamic-pvc-aa337a12-9ddb-11eb-ab3e-6e28514eb42d
{"event": "ConfigurationError: IO scheme k8s is undefined.", "level": "error", "timestamp": 1618768038.606371, "file": "/benji/lib64/python3.6/site-packages/benji/scripts/benji.py", "line": 373, "function": "main", "process": 4936, "thread_name": "MainThread", "thread_id": 140412611688256}
Traceback (most recent call last):
  File "/benji/bin/benji-backup-pvc", line 33, in <module>
    sys.exit(load_entry_point('benji-k8s-tools==0.1', 'console_scripts', 'benji-backup-pvc')())
  File "/benji/lib64/python3.6/site-packages/benji/k8s_tools/scripts/backup_pvc.py", line 335, in main
    context=context)
  File "/benji/lib64/python3.6/site-packages/benji/helpers/ceph.py", line 201, in backup
    exception=exception)
  File "/benji/lib64/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/benji/lib64/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/benji/lib64/python3.6/site-packages/benji/k8s_tools/scripts/backup_pvc.py", line 250, in ceph_backup_post_error
    raise exception
  File "/benji/lib64/python3.6/site-packages/benji/helpers/ceph.py", line 190, in backup
    context=context)
  File "/benji/lib64/python3.6/site-packages/benji/helpers/ceph.py", line 79, in backup_initial
    result = subprocess_run(benji_args, decode_json=True)
  File "/benji/lib64/python3.6/site-packages/benji/helpers/utils.py", line 65, in subprocess_run
    raise RuntimeError(f'{args[0]} invocation failed with return code {result.returncode} and output: {_one_line_stderr(result.stderr)}')
RuntimeError: benji invocation failed with return code 78 and output: {"event": "ConfigurationError: IO scheme k8s is undefined.", "level": "error", "timestamp": 1618768038.606371, "file": "/benji/lib64/python3.6/site-packages/benji/scripts/benji.py", "line": 373, "function": "main", "process": 4936, "thread_name": "MainThread", "thread_id": 140412611688256}
```

I'm running benji in k8s using the helm chart. External ceph cluster is connected to Kubernetes. Name of the ceph pool that is used is `k8s`.

Benji config:

```

configurationVersion: "1"
databaseEngine: postgresql://benji:secretpass@benji-postgresql-headless:5432/benji
defaultStorage: storage-1
ios:
- module: rbd
  name: rbd
  configuration:
    simultaneousReads: 3
    simultaneousWrites: 3
    cephConfigFile: /etc/ceph/ceph.conf
    clientIdentifier: admin
    newImageFeatures:
      - RBD_FEATURE_LAYERING
      - RBD_FEATURE_EXCLUSIVE_LOCK
      - RBD_FEATURE_STRIPINGV2
      - RBD_FEATURE_OBJECT_MAP
      - RBD_FEATURE_FAST_DIFF
      - RBD_FEATURE_DEEP_FLATTEN
storages:
  - name: storage-1
    module: s3
    configuration:
      awsAccessKeyId: SOMEKEY
      awsSecretAccessKey: SOMESECRET
      bucketName: benji
      endpointUrl: http://minio.address:9000/
```

 - Linux distribution name and version: `Ubuntu 18.04`

**Comment by elemental-lf** [comment]
The `benji-backup-pvc` command derives the name of the i/o scheme from the pool name. So if your pool is named `k8s` then the i/o scheme used in the backup command is also `k8s`. You need to adjust your `benji.conf` so that it defines an i/o module instance with the name `k8s`. In your case you just need to rename the i/o module instance `rbd` to `k8s`:

```yaml
ios:
- module: rbd
  name: k8s
  configuration:
# [...]
```

Let me know if this fixes things for you!

**Comment by kenandervisevic** [comment]
@elemental-lf that did the trick :) thanks for the help
