### ISSUE TITLE
Memory error on benji rm or benji enforce

### ISSUE THREAD

**Issue by chrstphfrtz** [elemental-lf/benji#138]
Hey! So we are testing benji for our Ceph cluster right now and have two RBD images which we want to backup regularly. So far everything works great except when running ```benji enforce``` or ```benji rm``` where we some errors.

```
[root@srv-ceph-01 ~]# benji enforce latest22
    INFO: Removing versions: production-jenkins-persistency-lbsyiy.
/usr/local/lib/python3.6/site-packages/benji/database.py:1476: SAWarning: Session's state has been changed on a non-active transaction - this state will be discarded.
  Session.rollback()
   ERROR: InvalidRequestError: This session is in 'inactive' state, due to the SQL transaction being rolled back; no further SQL can be emitted within this transaction.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/benji/database.py", line 377, in remove
    for affected_block in affected_blocks:
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/result.py", line 373, in iterrows
    uniques.add(hashed)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/benji/database.py", line 1530, in with_version_lock
    yield
  File "/usr/local/lib/python3.6/site-packages/benji/benji.py", line 697, in rm
    num_blocks = version.remove()
  File "/usr/local/lib/python3.6/site-packages/benji/database.py", line 390, in remove
    Session.rollback()
  File "<string>", line 2, in rollback
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1392, in rollback
    self._transaction.rollback(_to_root=self.future)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 874, in rollback
    dirty_only=transaction.nested
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 674, in _restore_snapshot
    to_expunge = set(self._new).union(self.session._new)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/benji/database.py", line 1470, in unlock
    Lock.process_id == self._process_id()).one_or_none()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 2836, in one_or_none
    return self._iter().one_or_none()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1643, in execute
    _parent_execute_state is not None,
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/context.py", line 298, in orm_pre_session_exec
    session._autoflush()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2223, in _autoflush
    self.flush()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 3345, in flush
    self._flush(objects)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 3380, in _flush
    new = set(self._new)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/benji/commands.py", line 339, in enforce_retention_policy
    group_label=group_label)
  File "/usr/local/lib/python3.6/site-packages/benji/benji.py", line 1147, in enforce_retention_policy
    self.rm(version.uid, force=True, keep_metadata_backup=keep_metadata_backup)
  File "/usr/local/lib/python3.6/site-packages/benji/benji.py", line 709, in rm
    logger.info('Removed backup version {} with {} blocks.'.format(version_uid, num_blocks))
  File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/benji/database.py", line 1532, in with_version_lock
    self.unlock_version(version_uid)
  File "/usr/local/lib/python3.6/site-packages/benji/database.py", line 1502, in unlock_version
    self.unlock(lock_name='Version {}'.format(version_uid))
  File "/usr/local/lib/python3.6/site-packages/benji/database.py", line 1476, in unlock
    Session.rollback()
  File "<string>", line 2, in rollback
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1392, in rollback
    self._transaction.rollback(_to_root=self.future)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 892, in rollback
    boundary._restore_snapshot(dirty_only=boundary.nested)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 674, in _restore_snapshot
    to_expunge = set(self._new).union(self.session._new)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/benji/scripts/benji.py", line 357, in main
    func(**func_args)
  File "/usr/local/lib/python3.6/site-packages/benji/commands.py", line 345, in enforce_retention_policy
    ignore_relationships=(((Version,), ('blocks',)),))
  File "/usr/local/lib/python3.6/site-packages/benji/benji.py", line 68, in __exit__
    self.close()
  File "/usr/local/lib/python3.6/site-packages/benji/benji.py", line 1031, in close
    Database.close()
  File "/usr/local/lib/python3.6/site-packages/benji/database.py", line 1398, in close
    Session.commit()
  File "<string>", line 2, in commit
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 827, in commit
    self._assert_active(prepared_ok=True)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 612, in _assert_active
    "This session is in 'inactive' state, due to the "
sqlalchemy.exc.InvalidRequestError: This session is in 'inactive' state, due to the SQL transaction being rolled back; no further SQL can be emitted within this transaction.
```
 This is the output of ```benji ls```

```
[root@srv-ceph-01 ~]# benji ls
+---------------------+---------------------------------------+--------------------------------+-----------------------+--------+------------+--------+-----------+------------+
|         date        | uid                                   | volume                         | snapshot              |   size | block_size | status | protected | storage    |
+---------------------+---------------------------------------+--------------------------------+-----------------------+--------+------------+--------+-----------+------------+
| 2022-01-07T00:10:43 | nexus-i3o85w                          | nexus                          | b-2022-01-07T00:00:02 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-08T00:15:17 | nexus-x6a8us                          | nexus                          | b-2022-01-08T00:00:02 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-09T00:26:51 | nexus-5qgdhf                          | nexus                          | b-2022-01-09T00:00:02 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-10T00:28:52 | nexus-f4lqt8                          | nexus                          | b-2022-01-10T00:00:03 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-11T00:30:03 | nexus-c7zm1c                          | nexus                          | b-2022-01-11T00:00:03 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-12T00:12:58 | nexus-7sc3n1                          | nexus                          | b-2022-01-12T00:00:02 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-13T00:20:27 | nexus-wdqex9                          | nexus                          | b-2022-01-13T00:00:02 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-14T00:12:21 | nexus-jeu4zl                          | nexus                          | b-2022-01-14T00:00:02 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-15T00:25:26 | nexus-a76awh                          | nexus                          | b-2022-01-15T00:00:03 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-16T00:30:19 | nexus-j2grhr                          | nexus                          | b-2022-01-16T00:00:02 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-17T00:15:41 | nexus-kxtq3v                          | nexus                          | b-2022-01-17T00:00:02 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-18T00:50:32 | nexus-1o13y9                          | nexus                          | b-2022-01-18T00:00:02 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-19T00:28:27 | nexus-hdkj8h                          | nexus                          | b-2022-01-19T00:00:03 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-20T00:23:18 | nexus-w8ou68                          | nexus                          | b-2022-01-20T00:00:02 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-21T00:30:33 | nexus-pp42jd                          | nexus                          | b-2022-01-21T00:00:03 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-22T00:29:31 | nexus-97dbqm                          | nexus                          | b-2022-01-22T00:00:03 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-23T00:36:39 | nexus-ahs81u                          | nexus                          | b-2022-01-23T00:00:03 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-24T00:13:17 | nexus-pj7s6f                          | nexus                          | b-2022-01-24T00:00:02 | 3.0TiB |     4.0MiB | valid  |   False   | production |
| 2021-12-29T18:08:43 | production-jenkins-persistency-lbsyiy | production-jenkins-persistency | b-2021-12-29T17:52:46 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-03T12:04:14 | production-jenkins-persistency-24nxt6 | production-jenkins-persistency | b-2022-01-03T11:34:06 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-04T01:33:31 | production-jenkins-persistency-hoqeav | production-jenkins-persistency | b-2022-01-04T00:30:02 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-05T02:33:37 | production-jenkins-persistency-asfcld | production-jenkins-persistency | b-2022-01-05T02:00:02 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-06T02:22:13 | production-jenkins-persistency-txzdyk | production-jenkins-persistency | b-2022-01-06T02:00:02 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-07T02:30:20 | production-jenkins-persistency-4lfdjc | production-jenkins-persistency | b-2022-01-07T02:00:02 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-08T02:29:35 | production-jenkins-persistency-2pcqzh | production-jenkins-persistency | b-2022-01-08T02:00:02 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-09T02:53:00 | production-jenkins-persistency-l88ciu | production-jenkins-persistency | b-2022-01-09T02:00:02 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-10T03:00:53 | production-jenkins-persistency-gnl1h5 | production-jenkins-persistency | b-2022-01-10T02:00:03 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-11T02:25:13 | production-jenkins-persistency-x1ggtp | production-jenkins-persistency | b-2022-01-11T02:00:02 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-12T02:24:26 | production-jenkins-persistency-qeifr0 | production-jenkins-persistency | b-2022-01-12T02:00:03 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-13T02:34:34 | production-jenkins-persistency-ful3fy | production-jenkins-persistency | b-2022-01-13T02:00:03 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-14T02:33:51 | production-jenkins-persistency-6qcstr | production-jenkins-persistency | b-2022-01-14T02:00:03 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-15T02:29:31 | production-jenkins-persistency-vg3gpx | production-jenkins-persistency | b-2022-01-15T02:00:02 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-16T02:55:08 | production-jenkins-persistency-u41zmu | production-jenkins-persistency | b-2022-01-16T02:00:03 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-17T02:37:23 | production-jenkins-persistency-vuxlbc | production-jenkins-persistency | b-2022-01-17T02:00:03 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-18T02:46:08 | production-jenkins-persistency-xsyted | production-jenkins-persistency | b-2022-01-18T02:00:02 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-19T02:29:50 | production-jenkins-persistency-mqb9rw | production-jenkins-persistency | b-2022-01-19T02:00:03 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-20T02:41:00 | production-jenkins-persistency-49wri7 | production-jenkins-persistency | b-2022-01-20T02:00:03 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-21T02:39:03 | production-jenkins-persistency-2bvv10 | production-jenkins-persistency | b-2022-01-21T02:00:03 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-22T02:43:23 | production-jenkins-persistency-7utgsa | production-jenkins-persistency | b-2022-01-22T02:00:03 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-23T02:57:04 | production-jenkins-persistency-3jyt6h | production-jenkins-persistency | b-2022-01-23T02:00:02 | 6.0TiB |     4.0MiB | valid  |   False   | production |
| 2022-01-24T02:51:53 | production-jenkins-persistency-84uwoj | production-jenkins-persistency | b-2022-01-24T02:00:03 | 6.0TiB |     4.0MiB | valid  |   False   | production |
+---------------------+---------------------------------------+--------------------------------+-----------------------+--------+------------+--------+-----------+------------+
```

So because we are only backing up two RBD images and we are testing it right now we started out with an SQlite database. Could it be the case that the SQlite database just can't handle the 6TiB snapshot? Any help is appreciated!

**Comment by elemental-lf** [comment]
I don't think that SQLite is the problem here. `MemoryError` is Python complaining that it has run out of memory. This might be a problem with SQLAlchemy or the way that we use it. Could you monitor the memory usage of Benji during the operation? How much memory does the machine have that you're running Benji on?

**Comment by elemental-lf** [comment]
I'm going to close this issue as there has been no feedback. Please reopen if you want to continue to work on this problem.
