### ISSUE TITLE
extras_require keys should not contain spaces

### ISSUE THREAD

**Issue by olifre** [elemental-lf/benji#2]
It seems not to work as intended:
```
pip install "benji[disk based read cache]"
pip install "benji[disk\ based\ read\ cache]"
pip install "benji[disk%20based%20read%20cache]"
```
all fail with something along the lines of:
```
Exception:
Traceback (most recent call last):
  File "/opt/benji/lib64/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/opt/benji/lib64/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1632, in parseString
    raise exc
  File "/opt/benji/lib64/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/opt/benji/lib64/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/benji/lib64/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/opt/benji/lib64/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/benji/lib64/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3183, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 11), (line:1, col:12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/benji/lib64/python3.6/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/opt/benji/lib64/python3.6/site-packages/pip/_internal/commands/install.py", line 274, in run
    self.name, wheel_cache
  File "/opt/benji/lib64/python3.6/site-packages/pip/_internal/basecommand.py", line 213, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/opt/benji/lib64/python3.6/site-packages/pip/_internal/req/req_install.py", line 248, in from_line
    extras = Requirement("placeholder" + extras.lower()).extras
  File "/opt/benji/lib64/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'[disk ba'"
```
Looking at:
https://github.com/loli/medpy/issues/49
it seems spaces do not work in the keys of `extras_require` (i.e. tooling does not like it).

**Comment by elemental-lf** [comment]
Thanks for the report, Oliver! This problem has been addressed in the current master.
