### ISSUE TITLE
Config Issues for RBD Features

### ISSUE THREAD

**Issue by adambmedent** [elemental-lf/benji#31]
Looking at this.

https://github.com/elemental-lf/benji/blob/master/etc/benji.yaml

Seems like this should work in my config file.  

  - name:
    module: rbd
     configuration:
       cephConfigFile: /etc/ceph/ceph.conf
      clientIdentifier: admin
       newImageFeatures:
        - RBD_FEATURE_LAYERING
        - RBD_FEATURE_EXCLUSIVE_LOCK
        - RBD_FEATURE_STRIPINGV2
        - RBD_FEATURE_OBJECT_MAP
        - RBD_FEATURE_FAST_DIFF
        - RBD_FEATURE_DEEP_FLATTEN

[root@ceph-backups ~]# /usr/local/benji/bin/benji ls
Uncaught exception
Traceback (most recent call last):
  File "/usr/local/benji/lib64/python3.6/site-packages/benji/config.py", line 144, in __init__
    config = ruamel.yaml.load(f, Loader=ruamel.yaml.SafeLoader)
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/main.py", line 935, in load
    return loader._constructor.get_single_data()
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/constructor.py", line 109, in get_single_data
    node = self.composer.get_single_node()
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/composer.py", line 78, in get_single_node
    document = self.compose_document()
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/composer.py", line 101, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/composer.py", line 218, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/composer.py", line 136, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/composer.py", line 180, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/composer.py", line 211, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/parser.py", line 141, in check_event
    self.current_event = self.state()
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/parser.py", line 563, in parse_block_mapping_key
    if self.scanner.check_token(KeyToken):
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/scanner.py", line 169, in check_token
    self.fetch_more_tokens()
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/scanner.py", line 321, in fetch_more_tokens
    self.reader.get_mark(),
ruamel.yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/etc/benji/benji.yaml", line 20, column 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/benji/bin/benji", line 11, in <module>
    load_entry_point('benji==0.4.0.dev6+gb61bef7', 'console_scripts', 'benji')()
  File "/usr/local/benji/lib64/python3.6/site-packages/benji/scripts/benji.py", line 297, in main
    config = Config()
  File "/usr/local/benji/lib64/python3.6/site-packages/benji/config.py", line 146, in __init__
    raise ConfigurationError('Configuration file {} is invalid.'.format(source)) from exception
benji.exception.ConfigurationError: Configuration file /etc/benji/benji.yaml is invalid.
[root@ceph-backups ~]#

**Comment by adambmedent** [comment]
Ahh so it seams formatting and spacing within the config is very important.  I got this one working.

  - name: rbd
    module: rbd
    configuration:
      cephConfigFile: /etc/ceph/ceph.conf
      clientIdentifier: admin
      newImageFeatures:
      - RBD_FEATURE_LAYERING
      - RBD_FEATURE_EXCLUSIVE_LOCK
      - RBD_FEATURE_STRIPINGV2
      - RBD_FEATURE_OBJECT_MAP
      - RBD_FEATURE_FAST_DIFF
      - RBD_FEATURE_DEEP_FLATTEN
      simultaneousReads: 10
      simultaneousWrites: 10

**Comment by elemental-lf** [comment]
Yes, YAML works that way ;)... Most distributions have a `yamllint` package and command that you can use to validate your configurations.
