### ISSUE TITLE
module 'b2' has no attribute 'bucket'

### ISSUE THREAD

**Issue by Gert-P** [elemental-lf/benji#49]
When trying to make a backup with benji to backblaze b2 i get this error:

`ERROR: An exception of type AttributeError occurred: module 'b2' has no attribute 'bucket'`

**Comment by elemental-lf** [comment]
Could you please provide the full stack trace of this error? Just start `benji` with `--log-level DEBUG`. Something like `benji --log-level DEBUG backup ...`. But my suspicion is that the bucket that you're referencing doesn't exist and that Benji doesn't generate an appropriate error message in that case. Could you make sure that the bucket exists and try again?

**Comment by Gert-P** [comment]
The output is identical with `--log-level DEBUG` added to it, the bucket definitely exist.

```
Uncaught exception
Traceback (most recent call last):
  File "/usr/local/benji/lib64/python3.6/site-packages/benji/config.py", line 144, in __init__
    config = ruamel.yaml.load(f, Loader=ruamel.yaml.SafeLoader)
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/main.py", line 935, in load
    return loader._constructor.get_single_data()
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/constructor.py", line 109, in get_single_data
    node = self.composer.get_single_node()
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/composer.py", line 78, in get_single_node
    document = self.compose_document()
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/composer.py", line 101, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/composer.py", line 218, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/composer.py", line 136, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/composer.py", line 180, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/composer.py", line 211, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/parser.py", line 141, in check_event
    self.current_event = self.state()
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/parser.py", line 563, in parse_block_mapping_key
    if self.scanner.check_token(KeyToken):
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/scanner.py", line 169, in check_token
    self.fetch_more_tokens()
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/scanner.py", line 282, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/benji/lib64/python3.6/site-packages/ruamel/yaml/scanner.py", line 655, in fetch_value
    self.reader.get_mark(),
ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
  in "/etc/benji.yaml", line 29, column 11

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/benji/bin/benji", line 11, in <module>
    sys.exit(main())
  File "/usr/local/benji/lib64/python3.6/site-packages/benji/scripts/benji.py", line 297, in main
    config = Config()
  File "/usr/local/benji/lib64/python3.6/site-packages/benji/config.py", line 146, in __init__
    raise ConfigurationError('Configuration file {} is invalid.'.format(source)) from exception
benji.exception.ConfigurationError: Configuration file /etc/benji.yaml is invalid.

```

**Comment by elemental-lf** [comment]
The stack trace you posted doesn't match up with your original error message. But I think I still figured out what's going on: The API of Backblaze's `b2` changed in version 1.4.0 because they are migrating to their new B2 SDK now. See https://github.com/elemental-lf/benji/issues/46. For the time being I'll pin the version to <=1.3.8. Please install the current master branch, make sure that your b2 package version is not 1.4.0 and retry. I've successfully tested the B2 access just now with 1.3.8.

**Comment by Gert-P** [comment]
Apologies, i sent the wrong stack trace, here is the correct one:

```
    INFO: $ /usr/local/benji/bin/benji --log-level DEBUG backup file:///temp/bigfile testbackup
   DEBUG: commands.backup(**{'base_version_uid': None, 'block_size': None, 'labels': None, 'rbd_hints': None, 'snapshot_name': '', 'source': 'file:///temp/bigfile', 'storage': '', 'version_name': 'testbackup'})
   DEBUG: Using block hash BLAKE2b with kwargs {'digest_bits': 256}.
   DEBUG: Resolved schema for benji.io.threaded-v1: {'configuration': {'type': 'dict', 'nullable': True, 'required': True, 'schema': {'simultaneousWrites': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}, 'simultaneousReads': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}}}}.
   DEBUG: Resolved schema for benji.io.file-v1: {'configuration': {'type': 'dict', 'nullable': True, 'required': True, 'schema': {'simultaneousWrites': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}, 'simultaneousReads': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}}}}.
   DEBUG: Resolved schema for benji.storage.base-v1: {'configuration': {'type': 'dict', 'empty': False, 'schema': {'activeTransforms': {'type': 'list', 'empty': False, 'schema': {'type': 'string', 'empty': False}}, 'simultaneousWrites': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}, 'simultaneousReads': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}, 'simultaneousRemovals': {'type': 'integer', 'empty': False, 'min': 1, 'default': 5}, 'bandwidthRead': {'type': 'integer', 'empty': False, 'min': 0, 'default': 0}, 'bandwidthWrite': {'type': 'integer', 'empty': False, 'min': 0, 'default': 0}, 'consistencyCheckWrites': {'type': 'boolean', 'empty': False, 'default': False}, 'hmac': {'type': 'dict', 'empty': False, 'schema': {'password': {'type': 'string', 'empty': False, 'required': True, 'minlength': 8}, 'kdfSalt': {'type': 'string', 'empty': False, 'required': True}, 'kdfIterations': {'type': 'integer', 'empty': False, 'required': True, 'min': 1000}}}}}}.
   DEBUG: Resolved schema for benji.storage.file-v1: {'configuration': {'type': 'dict', 'empty': False, 'schema': {'activeTransforms': {'type': 'list', 'empty': False, 'schema': {'type': 'string', 'empty': False}}, 'simultaneousWrites': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}, 'simultaneousReads': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}, 'simultaneousRemovals': {'type': 'integer', 'empty': False, 'min': 1, 'default': 5}, 'bandwidthRead': {'type': 'integer', 'empty': False, 'min': 0, 'default': 0}, 'bandwidthWrite': {'type': 'integer', 'empty': False, 'min': 0, 'default': 0}, 'consistencyCheckWrites': {'type': 'boolean', 'empty': False, 'default': False}, 'hmac': {'type': 'dict', 'empty': False, 'schema': {'password': {'type': 'string', 'empty': False, 'required': True, 'minlength': 8}, 'kdfSalt': {'type': 'string', 'empty': False, 'required': True}, 'kdfIterations': {'type': 'integer', 'empty': False, 'required': True, 'min': 1000}}}, 'path': {'type': 'string', 'empty': False, 'required': True}}, 'required': True}}.
   DEBUG: Resolved schema for benji.storage.base-v1: {'configuration': {'type': 'dict', 'empty': False, 'schema': {'activeTransforms': {'type': 'list', 'empty': False, 'schema': {'type': 'string', 'empty': False}}, 'simultaneousWrites': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}, 'simultaneousReads': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}, 'simultaneousRemovals': {'type': 'integer', 'empty': False, 'min': 1, 'default': 5}, 'bandwidthRead': {'type': 'integer', 'empty': False, 'min': 0, 'default': 0}, 'bandwidthWrite': {'type': 'integer', 'empty': False, 'min': 0, 'default': 0}, 'consistencyCheckWrites': {'type': 'boolean', 'empty': False, 'default': False}, 'hmac': {'type': 'dict', 'empty': False, 'schema': {'password': {'type': 'string', 'empty': False, 'required': True, 'minlength': 8}, 'kdfSalt': {'type': 'string', 'empty': False, 'required': True}, 'kdfIterations': {'type': 'integer', 'empty': False, 'required': True, 'min': 1000}}}}}}.
   DEBUG: Resolved schema for benji.storage.base.ReadCache-v1: {'configuration': {'type': 'dict', 'empty': False, 'schema': {'activeTransforms': {'type': 'list', 'empty': False, 'schema': {'type': 'string', 'empty': False}}, 'simultaneousWrites': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}, 'simultaneousReads': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}, 'simultaneousRemovals': {'type': 'integer', 'empty': False, 'min': 1, 'default': 5}, 'bandwidthRead': {'type': 'integer', 'empty': False, 'min': 0, 'default': 0}, 'bandwidthWrite': {'type': 'integer', 'empty': False, 'min': 0, 'default': 0}, 'consistencyCheckWrites': {'type': 'boolean', 'empty': False, 'default': False}, 'hmac': {'type': 'dict', 'empty': False, 'schema': {'password': {'type': 'string', 'empty': False, 'required': True, 'minlength': 8}, 'kdfSalt': {'type': 'string', 'empty': False, 'required': True}, 'kdfIterations': {'type': 'integer', 'empty': False, 'required': True, 'min': 1000}}}, 'readCache': {'type': 'dict', 'empty': False, 'schema': {'directory': {'type': 'string', 'required': True, 'empty': False, 'dependencies': ['maximumSize', 'shards']}, 'maximumSize': {'type': 'integer', 'required': True, 'min': 1, 'dependencies': ['directory', 'shards']}, 'shards': {'type': 'integer', 'required': True, 'min': 1, 'dependencies': ['directory', 'maximumSize']}}}}, 'required': True}}.
   DEBUG: Resolved schema for benji.storage.b2-v1: {'configuration': {'type': 'dict', 'empty': False, 'schema': {'activeTransforms': {'type': 'list', 'empty': False, 'schema': {'type': 'string', 'empty': False}}, 'simultaneousWrites': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}, 'simultaneousReads': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}, 'simultaneousRemovals': {'type': 'integer', 'empty': False, 'min': 1, 'default': 5}, 'bandwidthRead': {'type': 'integer', 'empty': False, 'min': 0, 'default': 0}, 'bandwidthWrite': {'type': 'integer', 'empty': False, 'min': 0, 'default': 0}, 'consistencyCheckWrites': {'type': 'boolean', 'empty': False, 'default': False}, 'hmac': {'type': 'dict', 'empty': False, 'schema': {'password': {'type': 'string', 'empty': False, 'required': True, 'minlength': 8}, 'kdfSalt': {'type': 'string', 'empty': False, 'required': True}, 'kdfIterations': {'type': 'integer', 'empty': False, 'required': True, 'min': 1000}}}, 'readCache': {'type': 'dict', 'empty': False, 'schema': {'directory': {'type': 'string', 'required': True, 'empty': False, 'dependencies': ['maximumSize', 'shards']}, 'maximumSize': {'type': 'integer', 'required': True, 'min': 1, 'dependencies': ['directory', 'shards']}, 'shards': {'type': 'integer', 'required': True, 'min': 1, 'dependencies': ['directory', 'maximumSize']}}}, 'accountId': {'type': 'string', 'required': True, 'empty': False, 'excludes': ['accountIdFile']}, 'accountIdFile': {'type': 'string', 'required': True, 'empty': False, 'excludes': ['accountId']}, 'applicationKey': {'type': 'string', 'required': True, 'empty': False, 'excludes': ['applicationKeyFile']}, 'applicationKeyFile': {'type': 'string', 'required': True, 'empty': False, 'excludes': ['applicationKey']}, 'bucketName': {'type': 'string', 'required': True, 'empty': False}, 'accountInfoFile': {'type': 'string', 'empty': False}, 'uploadAttempts': {'type': 'integer', 'empty': False, 'default': 5, 'min': 1}, 'writeObjectAttempts': {'type': 'integer', 'empty': False, 'default': 3, 'min': 1}, 'readObjectAttempts': {'type': 'integer', 'empty': False, 'default': 3, 'min': 1}}, 'required': True}}.
   DEBUG: Current database schema revision: 368014edd88c.
   DEBUG: Expected database schema revision: 368014edd88c.
   DEBUG: AttributeError: module 'b2' has no attribute 'bucket'
Traceback (most recent call last):
  File "/usr/local/benji/lib64/python3.6/site-packages/benji/scripts/benji.py", line 331, in main
    func(**func_args)
  File "/usr/local/benji/lib64/python3.6/site-packages/benji/commands.py", line 51, in backup
    backup_version = benji_obj.backup(version_name, snapshot_name, source, hints, base_version_uid_obj, storage)
  File "/usr/local/benji/lib64/python3.6/site-packages/benji/benji.py", line 840, in backup
    storage = StorageFactory.get_by_storage_id(version.storage_id)
  File "/usr/local/benji/lib64/python3.6/site-packages/benji/factory.py", line 90, in get_by_storage_id
    cls._instances[storage_id] = module.Storage(**module_arguments)
  File "/usr/local/benji/lib64/python3.6/site-packages/benji/storage/b2.py", line 49, in __init__
    b2.bucket.Bucket.MAX_UPLOAD_ATTEMPTS = Config.get_from_dict(module_configuration, 'uploadAttempts', types=int)
AttributeError: module 'b2' has no attribute 'bucket'
   ERROR: AttributeError: module 'b2' has no attribute 'bucket'

```

I will install again from master branch and let you know.

**Comment by Gert-P** [comment]
Indeed it is working now as expected. Thank you.
