### ISSUE TITLE
benji storage-usage fails, complains something about blocks.size

### ISSUE THREAD

**Issue by vvolas** [elemental-lf/benji#95]
I m testing benji, installed as recommended in python venv + system packags support for ceph.

I backuped few rbd images, and tried to look how much space is used with `benji storage-usage` and it fails. I tried fresh start deleted db, deleted storage and it still fails with same error. I tried adding block size into config didint do anything.

So it can be reproduced with
1) database-init
2) storage-usage

```
configurationVersion: '1'
logFile: /var/log/benji/benji.log
disallowRemoveWhenYounger: 6
databaseEngine: postgresql://benji:xxx@localhost:5432/benji
defaultStorage: ceph-lxd
transforms:
  - name: zstd
    module: zstd
    configuration:
      level: 10
storages:
  - name: ceph-lxd
    module: file
    configuration:
      path: /srv/backups/benji-ceph-lxd
      simultaneousReads: 3
      simultaneousWrites: 3
      activeTransforms:
        - zstd
ios:
  - name: rbd
    module: rbd
    configuration:
      simultaneousReads: 2
      simultaneousWrites: 2

```
```

    INFO: Benji version: 0.10.0.
    INFO: Configuration version: 1.0.0, supported >=1,<2.
    INFO: Metadata version: 3.0.0, supported >=1,<4.
    INFO: Object metadata version: 2.0.0, supported >=1,<3.
```
5.3.0-59-generic #53~18.04.1-Ubuntu SMP Thu Jun 4 14:58:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Python 3.6.9

```
root@blackhole:~# /usr/local/benji/bin/benji --log-level DEBUG storage-usage
   DEBUG: Resolved schema for benji.io.rbd-v1: {'configuration': {'type': 'dict', 'required': True, 'empty': False, 'schema': {'simultaneousWrites': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}, 'simultaneousReads': {'type': 'integer', 'empty': False, 'min
': 1, 'default': 3}, 'cephConfigFile': {'type': 'string', 'empty': False, 'default': '/etc/ceph/ceph.conf'}, 'clientIdentifier': {'type': 'string', 'empty': False, 'default': 'admin'}, 'newImageFeatures': {'type': 'list', 'empty': False, 'default': ['RBD_FEATURE_LAYERING
'], 'schema': {'type': 'string', 'regex': '^RBD_FEATURE_.*'}}}}}.                                   
   DEBUG: Resolved schema for benji.transform.zstd-v1: {'configuration': {'schema': {'level': {'type': 'integer', 'empty': False, 'default': 3, 'min': 1}, 'dictDataFile': {'type': 'string', 'empty': False}}}}.
   DEBUG: Resolved schema for benji.storage.base-v1: {'configuration': {'type': 'dict', 'empty': False, 'schema': {'activeTransforms': {'type': 'list', 'empty': False, 'schema': {'type': 'string', 'empty': False}}, 'simultaneousWrites': {'type': 'integer', 'empty': False
, 'min': 1, 'default': 3}, 'simultaneousReads': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}, 'simultaneousRemovals': {'type': 'integer', 'empty': False, 'min': 1, 'default': 5}, 'bandwidthRead': {'type': 'integer', 'empty': False, 'min': 0, 'default': 0},
 'bandwidthWrite': {'type': 'integer', 'empty': False, 'min': 0, 'default': 0}, 'consistencyCheckWrites': {'type': 'boolean', 'empty': False, 'default': False}, 'hmac': {'type': 'dict', 'empty': False, 'schema': {'password': {'type': 'string', 'empty': False, 'required':
 True, 'minlength': 8}, 'kdfSalt': {'type': 'string', 'empty': False, 'required': True}, 'kdfIterations': {'type': 'integer', 'empty': False, 'required': True, 'min': 1000}}}}}}.
   DEBUG: Resolved schema for benji.storage.file-v1: {'configuration': {'type': 'dict', 'empty': False, 'schema': {'activeTransforms': {'type': 'list', 'empty': False, 'schema': {'type': 'string', 'empty': False}}, 'simultaneousWrites': {'type': 'integer', 'empty': False
, 'min': 1, 'default': 3}, 'simultaneousReads': {'type': 'integer', 'empty': False, 'min': 1, 'default': 3}, 'simultaneousRemovals': {'type': 'integer', 'empty': False, 'min': 1, 'default': 5}, 'bandwidthRead': {'type': 'integer', 'empty': False, 'min': 0, 'default': 0},
 'bandwidthWrite': {'type': 'integer', 'empty': False, 'min': 0, 'default': 0}, 'consistencyCheckWrites': {'type': 'boolean', 'empty': False, 'default': False}, 'hmac': {'type': 'dict', 'empty': False, 'schema': {'password': {'type': 'string', 'empty': False, 'required':
 True, 'minlength': 8}, 'kdfSalt': {'type': 'string', 'empty': False, 'required': True}, 'kdfIterations': {'type': 'integer', 'empty': False, 'required': True, 'min': 1000}}}, 'path': {'type': 'string', 'empty': False, 'required': True}}, 'required': True}}.
   DEBUG: commands.storage_usage(**{'filter_expression': None})                                                                                                                                                                                       
   DEBUG: Using block hash BLAKE2b with kwargs {'digest_bits': 256}.                                                                                            
   DEBUG: Current database schema revision: 3d014d45493f.                                                                                   
   DEBUG: Expected database schema revision: 3d014d45493f.                                                      
   DEBUG: Found existing storage ceph-lxd with id 1.                                                                                      
   ERROR: ProgrammingError: (psycopg2.errors.GroupingError) column "blocks.size" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...s_uid_left, blocks.uid_right AS blocks_uid_right, blocks.siz...

[SQL: SELECT storages.id AS storage_id, storages.name AS storage_name, blocks.uid_left AS blocks_uid_left, blocks.uid_right AS blocks_uid_right, blocks.size AS size, count(%(count_1)s) AS share_count_subset, (SELECT count(%(count_3)s) AS count_2 
FROM blocks AS blocks_1 JOIN versions AS versions_1 ON versions_1.id = blocks_1.version_id JOIN storages AS storages_1 ON storages_1.id = versions_1.storage_id 
WHERE storages.id = storages_1.id AND blocks.uid_left = blocks_1.uid_left AND blocks.uid_right = blocks_1.uid_right) AS share_count_overall 
FROM blocks JOIN versions ON versions.id = blocks.version_id JOIN storages ON storages.id = versions.storage_id 
WHERE blocks.uid_left IS NOT NULL AND blocks.uid_right IS NOT NULL GROUP BY storages.id, storages.name, blocks.uid_left, blocks.uid_right]
[parameters: {'count_1': '*', 'count_3': '*'}]
(Background on this error at: http://sqlalche.me/e/13/f405)
Traceback (most recent call last):
  File "/usr/local/benji/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/benji/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.GroupingError: column "blocks.size" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...s_uid_left, blocks.uid_right AS blocks_uid_right, blocks.siz...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/benji/lib/python3.6/site-packages/benji/scripts/benji.py", line 357, in main
    func(**func_args)
  File "/usr/local/benji/lib/python3.6/site-packages/benji/commands.py", line 442, in storage_usage
    usage = benji_obj.storage_usage(filter_expression)
  File "/usr/local/benji/lib/python3.6/site-packages/benji/benji.py", line 1157, in storage_usage
    return Version.storage_usage(filter_expression)
  File "/usr/local/benji/lib/python3.6/site-packages/benji/database.py", line 630, in storage_usage
    for row in share_count_query.all():
  File "/usr/local/benji/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3346, in all
    return list(self)
  File "/usr/local/benji/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/benji/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/benji/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/benji/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/benji/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/usr/local/benji/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/benji/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/benji/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/benji/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/benji/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.GroupingError) column "blocks.size" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...s_uid_left, blocks.uid_right AS blocks_uid_right, blocks.siz...
                                                             ^

[SQL: SELECT storages.id AS storage_id, storages.name AS storage_name, blocks.uid_left AS blocks_uid_left, blocks.uid_right AS blocks_uid_right, blocks.size AS size, count(%(count_1)s) AS share_count_subset, (SELECT count(%(count_3)s) AS count_2 
FROM blocks AS blocks_1 JOIN versions AS versions_1 ON versions_1.id = blocks_1.version_id JOIN storages AS storages_1 ON storages_1.id = versions_1.storage_id 
WHERE storages.id = storages_1.id AND blocks.uid_left = blocks_1.uid_left AND blocks.uid_right = blocks_1.uid_right) AS share_count_overall 
FROM blocks JOIN versions ON versions.id = blocks.version_id JOIN storages ON storages.id = versions.storage_id 
WHERE blocks.uid_left IS NOT NULL AND blocks.uid_right IS NOT NULL GROUP BY storages.id, storages.name, blocks.uid_left, blocks.uid_right]
[parameters: {'count_1': '*', 'count_3': '*'}]
(Background on this error at: http://sqlalche.me/e/13/f405)

```

**Comment by elemental-lf** [comment]
Thanks for your report! I just tried to reproduce with PostgreSQL 10, 11 and 12 and couldn't. What PostgreSQL version are you using?

EDIT: My bad! I tested the wrong command, doh! I can reproduce it now. Will look into it.

**Comment by elemental-lf** [comment]
@vvolas I just pushed a fix for your problem and also added a test to better catch bugs in this area in the future.
