### ISSUE TITLE
benji storage-usage fails with TypeError: unsupported operand type(s) for /=: 'decimal.Decimal' and 'float'

### ISSUE THREAD

**Issue by vvolas** [elemental-lf/benji#96]
Hello I updated benji to 11.0

Now `storage-usage` gives different error. 
```

root@blackhole:~# /usr/local/benji/bin/benji storage-usage
   ERROR: TypeError: unsupported operand type(s) for /=: 'decimal.Decimal' and 'float'
Traceback (most recent call last):
  File "/usr/local/benji/lib/python3.6/site-packages/benji/scripts/benji.py", line 357, in main
    func(**func_args)
  File "/usr/local/benji/lib/python3.6/site-packages/benji/commands.py", line 446, in storage_usage
    self._storage_usage_table_output(usage)
  File "/usr/local/benji/lib/python3.6/site-packages/benji/commands.py", line 431, in _storage_usage_table_output
    PrettyPrint.bytes(usage['virtual']),
  File "/usr/local/benji/lib/python3.6/site-packages/benji/utils.py", line 136, in bytes
    num /= 1024.0
TypeError: unsupported operand type(s) for /=: 'decimal.Decimal' and 'float'
```

ubuntu18
Python 3.6.9

```
(benji) root@blackhole:/usr/local# pip list
Package            Version
------------------ -------------------
alembic            1.4.3
argcomplete        1.12.0
asn1crypto         0.24.0
attrs              17.4.0
Automat            0.6.0
benji              0.11.0
bottle             0.12.13
ceph               1.0.0
cephfs             2.0.0 
Cerberus           1.3.2
certifi            2018.1.18
chardet            3.0.4    
click              6.7   
colorama           0.4.3
command-not-found  0.3     
configobj          5.0.6   
constantly         15.1.0
croniter           0.3.12
cryptography       2.1.4 
cycler             0.10.0
dateparser         0.7.6 
diskcache          5.0.3 
distro-info        0.18ubuntu0.18.04.1
docker             2.5.1
docker-pycreds     0.2.1 
Glances            2.11.1
hyperlink          17.3.1
idna               2.6
importlib-metadata 1.7.0
incremental        16.10.1
influxdb           4.1.1
Jinja2             2.10
keyring            10.6.0
keyrings.alt       3.0   
language-selector  0.1   
Mako               1.1.3
MarkupSafe         1.0  
matplotlib         2.1.1 
msgpack            0.5.6          
netifaces          0.10.4
numpy              1.16.0
olefile            0.45.1
PAM                0.4.2
Pillow             5.1.0
pip                9.0.1
pkg-resources      0.0.0
ply                3.11
prettytable        0.7.2
psutil             5.4.2
psycopg2-binary    2.8.6
pyasn1             0.4.2
pyasn1-modules     0.2.1
pycrypto           2.6.1
pycryptodome       3.9.8
pycryptodomex      3.4.7
pygobject          3.26.1
pyOpenSSL          17.5.0
pyparsing          2.4.7
pyserial           3.4
pysmi              0.2.2
pysnmp             4.4.3
pystache           0.5.4
python-apt         1.6.5+ubuntu0.3
python-dateutil    2.6.1
python-debian      0.1.32
python-editor      1.0.4
python-gnupg       0.4.1
python3-lxc        3.0.1
pytz               2018.3
pyxdg              0.25
PyYAML             3.12
pyzmq              16.0.2
rados              2.0.0
rbd                2.0.0
regex              2020.7.14
requests           2.18.4
rgw                2.0.0
ruamel.yaml        0.15.100
salt               2019.2.5
SecretStorage      2.3.1
semantic-version   2.8.5
service-identity   16.0.0
setproctitle       1.1.10
setuptools         39.0.1
six                1.11.0
sortedcontainers   2.2.2
sparsebitfield     0.2.3
SQLAlchemy         1.3.19
ssh-import-id      5.7
structlog          20.1.0
systemd-python     234
tornado            4.5.3
Twisted            17.9.0
tzlocal            2.1
ufw                0.36
urllib3            1.22
websocket-client   0.44.0
wheel              0.30.0
zipp               3.1.0
zope.interface     4.3.2
zstandard          0.14.0

```

**Comment by wech71** [comment]
Hi,

I get the same error (postgres 10) with benji 0.11.0

**Comment by elemental-lf** [comment]
@vvolas, @wech71, thanks for the report, both of you! I've just pushed a fix which should make `benji storage-usage` actually usable. I'm not 100% sure what happened here in the first place but I suspect that I tested this command with SQLite only while coding it. I've augmented the tests to catch this error in the future.

**Comment by wech71** [comment]
Sorry for the late feedback, but it works now. Thank you! :-)
